
import __ASTRO_IMAGE_IMPORT_0 from "./images/cloudsync-suite/1.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fcloudsync-suite.md";
import __ASTRO_IMAGE_IMPORT_1 from "./images/cloudsync-suite/2.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fcloudsync-suite.md";
import __ASTRO_IMAGE_IMPORT_2 from "./images/cloudsync-suite/3.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fcloudsync-suite.md";
import __ASTRO_IMAGE_IMPORT_3 from "./images/cloudsync-suite/4.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fcloudsync-suite.md";
import __ASTRO_IMAGE_IMPORT_4 from "./images/coffee-brand/1.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fcoffee-brand.md";
import __ASTRO_IMAGE_IMPORT_5 from "./images/coffee-brand/2.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fcoffee-brand.md";
import __ASTRO_IMAGE_IMPORT_6 from "./images/coffee-brand/3.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fcoffee-brand.md";
import __ASTRO_IMAGE_IMPORT_7 from "./images/coffee-brand/4.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fcoffee-brand.md";
import __ASTRO_IMAGE_IMPORT_8 from "./images/lumina/1.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Flumina.md";
import __ASTRO_IMAGE_IMPORT_9 from "./images/lumina/2.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Flumina.md";
import __ASTRO_IMAGE_IMPORT_10 from "./images/lumina/3.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Flumina.md";
import __ASTRO_IMAGE_IMPORT_11 from "./images/lumina/4.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Flumina.md";
import __ASTRO_IMAGE_IMPORT_12 from "./images/nourish/1.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fnourish-restaurant.md";
import __ASTRO_IMAGE_IMPORT_13 from "./images/nourish/2.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fnourish-restaurant.md";
import __ASTRO_IMAGE_IMPORT_14 from "./images/nourish/3.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fnourish-restaurant.md";
import __ASTRO_IMAGE_IMPORT_15 from "./images/nourish/4.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fnourish-restaurant.md";
import __ASTRO_IMAGE_IMPORT_16 from "./images/smart-speaker/1.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fsmart-speaker.md";
import __ASTRO_IMAGE_IMPORT_17 from "./images/smart-speaker/2.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fsmart-speaker.md";
import __ASTRO_IMAGE_IMPORT_18 from "./images/smart-speaker/3.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fsmart-speaker.md";
import __ASTRO_IMAGE_IMPORT_19 from "./images/smart-speaker/4.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fsmart-speaker.md";
import __ASTRO_IMAGE_IMPORT_20 from "./images/zenith-wellness/1.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fzenith-wellness.md";
import __ASTRO_IMAGE_IMPORT_21 from "./images/zenith-wellness/2.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fzenith-wellness.md";
import __ASTRO_IMAGE_IMPORT_22 from "./images/zenith-wellness/3.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fzenith-wellness.md";
import __ASTRO_IMAGE_IMPORT_23 from "./images/zenith-wellness/4.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fzenith-wellness.md";
export default new Map([["./images/cloudsync-suite/1.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fcloudsync-suite.md", __ASTRO_IMAGE_IMPORT_0], ["./images/cloudsync-suite/2.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fcloudsync-suite.md", __ASTRO_IMAGE_IMPORT_1], ["./images/cloudsync-suite/3.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fcloudsync-suite.md", __ASTRO_IMAGE_IMPORT_2], ["./images/cloudsync-suite/4.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fcloudsync-suite.md", __ASTRO_IMAGE_IMPORT_3], ["./images/coffee-brand/1.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fcoffee-brand.md", __ASTRO_IMAGE_IMPORT_4], ["./images/coffee-brand/2.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fcoffee-brand.md", __ASTRO_IMAGE_IMPORT_5], ["./images/coffee-brand/3.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fcoffee-brand.md", __ASTRO_IMAGE_IMPORT_6], ["./images/coffee-brand/4.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fcoffee-brand.md", __ASTRO_IMAGE_IMPORT_7], ["./images/lumina/1.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Flumina.md", __ASTRO_IMAGE_IMPORT_8], ["./images/lumina/2.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Flumina.md", __ASTRO_IMAGE_IMPORT_9], ["./images/lumina/3.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Flumina.md", __ASTRO_IMAGE_IMPORT_10], ["./images/lumina/4.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Flumina.md", __ASTRO_IMAGE_IMPORT_11], ["./images/nourish/1.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fnourish-restaurant.md", __ASTRO_IMAGE_IMPORT_12], ["./images/nourish/2.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fnourish-restaurant.md", __ASTRO_IMAGE_IMPORT_13], ["./images/nourish/3.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fnourish-restaurant.md", __ASTRO_IMAGE_IMPORT_14], ["./images/nourish/4.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fnourish-restaurant.md", __ASTRO_IMAGE_IMPORT_15], ["./images/smart-speaker/1.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fsmart-speaker.md", __ASTRO_IMAGE_IMPORT_16], ["./images/smart-speaker/2.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fsmart-speaker.md", __ASTRO_IMAGE_IMPORT_17], ["./images/smart-speaker/3.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fsmart-speaker.md", __ASTRO_IMAGE_IMPORT_18], ["./images/smart-speaker/4.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fsmart-speaker.md", __ASTRO_IMAGE_IMPORT_19], ["./images/zenith-wellness/1.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fzenith-wellness.md", __ASTRO_IMAGE_IMPORT_20], ["./images/zenith-wellness/2.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fzenith-wellness.md", __ASTRO_IMAGE_IMPORT_21], ["./images/zenith-wellness/3.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fzenith-wellness.md", __ASTRO_IMAGE_IMPORT_22], ["./images/zenith-wellness/4.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fzenith-wellness.md", __ASTRO_IMAGE_IMPORT_23]]);
		